apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r7omrxxwe-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b186860284.chec.p3.openshiftapps.com/rhtap/rhtap-qe:eba9b28bb2bf4463922a1890d2ab94232e68d11d@sha256:f2a2578245fec721a9542b883ebad0ed0070c9df6d130041bbea6d5829ba9263
          name: container-image
